project_id = "xkybsjnvuohpqpbkikyn"

[functions]

# region = "iad1"

[functions.register]
verify_jwt = false

[functions.sms-send-code]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false

[functions.system-status]
verify_jwt = false
